spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <adicione aqui>
            client-secret: <adicione aqui>
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

#endereço para criar credentials no google (https://console.cloud.google.com/apis/credentials)
#endereço da aplicação adicionado na credential , url de redirecionamento autorizados (http://localhost://login/oauth2/code/google)
          
